services:
  redchef:
    build: .
    ports:
      - "6270:6270"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      PORT: "6270"
      DB_PATH: /db/redchef.db
      UPLOAD_DIR: /app/media
    volumes:
      - redchef_media:/app/media
      - redchef_db:/db

volumes:
  redchef_media:
  redchef_db:
